-- MySQL Script generated by MySQL Workbench
-- Fri Mar 24 21:47:16 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema agendadb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `agendadb` ;

-- -----------------------------------------------------
-- Schema agendadb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `agendadb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `agendadb` ;

-- -----------------------------------------------------
-- Table `agendadb`.`contacto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `agendadb`.`contacto` (
  `idContac` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nombre` VARCHAR(100) NOT NULL COMMENT '',
  `direccion` VARCHAR(200) NOT NULL COMMENT '',
  `email` VARCHAR(50) NULL COMMENT '',
  `telefono` VARCHAR(15) NOT NULL COMMENT '',
  `celular` VARCHAR(15) NULL COMMENT '',
  PRIMARY KEY (`idContac`)  COMMENT '',
  UNIQUE INDEX `idcontac_UNIQUE` (`idContac` ASC)  COMMENT '')
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
