<!-- CODIGO ORIGINAL < ? php echo $this->layout()->content; ?>-->
<!-- application/layouts/scripts/layout.phtml -->
<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
      <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
      <title>Agenda ZF1</title>
      <?= $this->headLink()->appendStylesheet('/css/bootstrap.min.css') ?>
      <?= $this->headLink()->appendStylesheet('/css/modern-business.css') ?>
      <?= $this->headLink()->appendStylesheet('/css/font-awesome.min.css') ?>
    </head>
    <body>
        
    <!-- Navigation -->
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/">Agenda Test</a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a href="<?php echo $this->url(
                            array('controller'=>'contacto'),
                                  'default', true) ?>">
                            Listar Contactos
                        </a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

        <?php echo $this->layout()->content ?>

    </body>
</html>